"""empty message

Revision ID: 1aa0443d72cf
Revises: aae080c57957
Create Date: 2025-06-04 21:56:32.632044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa0443d72cf'
down_revision = 'aae080c57957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mail_notify', sa.Boolean(), nullable=True))
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('mail_notify')

    # ### end Alembic commands ###
