"""empty message

Revision ID: 3ee45d1ebca4
Revises: 57c258179020
Create Date: 2025-05-28 22:14:47.028577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ee45d1ebca4'
down_revision = '57c258179020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.Integer(), nullable=True))
        batch_op.alter_column('priority',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.INTEGER(), nullable=False))
        batch_op.alter_column('priority',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('state')

    # ### end Alembic commands ###
