"""empty message

Revision ID: 4586bf6eba32
Revises: 3fa455d1cc40
Create Date: 2025-06-08 13:43:42.106004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4586bf6eba32'
down_revision = '3fa455d1cc40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Integer(), nullable=True))
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.INTEGER(), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
