"""empty message

Revision ID: aae080c57957
Revises: b56b1be800f4
Create Date: 2025-06-04 00:05:28.803381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aae080c57957'
down_revision = 'b56b1be800f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('completed_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_data', sa.DATETIME(), nullable=True))
        batch_op.drop_column('completed_time')

    # ### end Alembic commands ###
