"""empty message

Revision ID: b56b1be800f4
Revises: d780a4f6b193
Create Date: 2025-06-03 23:12:41.612948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56b1be800f4'
down_revision = 'd780a4f6b193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DATETIME(), nullable=True))
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
